volumes:
  init-db:
  data-db:

services:
  db:
    image: mongodb/mongodb-community-server:7.0.2-ubi8
    ports:
      - "27017:27017"
    container_name: mongo_container1
    networks:
      - backend

  app:
    build: .
    volumes:
      - .:/djangoProject
    ports:
      - "8000:8000"
    image: app:djangoProject
    container_name: blog_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - backend
networks:
  backend: